#define CREER_EQUIPE "CREER_EQUIPE"
#define REJOINDRE_EQUIPE "REJOINDRE_EQUIPE"
#define QUITTER_EQUIPE "QUITTER_EQUIPE"
#define MENU_JOUEUR "MENU_JOUEUR"
#define MENU_CHOIX_EQ "MENU_CHOIX_EQ"
#define START "START"
#define END "END"
#define DEPLACEMENT "DEPLACEMENT"
#define TIR "TIR"
#define RECHARGEMENT "RECHARGEMENT"
#define TIMEOUT "TIMEOUT"
#define PSEUDO_POK "PSEUDO_POK"
#define DISABLE_BUTT "DISABLE_BUTT"
#define MODE_JEUX "MODE_JEUX"
#define INVITER_AMI "INVITER_AMI"
#define NEW_BUTT "NEW_BUTT"
#define KICK_AMI "KICK_AMI"

/* pour comparer sur ce nombre et pas les paramètres suivant */
#define TAILLE_REJ 16
#define TAILLE_DEP 11
#define TAILLE_TIR 3
#define TAILLE_RECH 12
