#define CREER_EQUIPE "CREER_EQUIPE"
#define REJOINDRE_EQUIPE "REJOINDRE_EQUIPE"
#define QUITTER_EQUIPE "QUITTER_EQUIPE"
#define MENU_JOUEUR "MENU_JOUEUR"
#define MENU_CHOIX_EQ "MENU_CHOIX_EQ"
#define START "START"
#define END "END"
#define DEPLACEMENT "DEPLACEMENT"
#define TIR "TIR"
#define PSEUDO_POK "PSEUDO_POK"
#define MODE_JEUX "MODE_JEUX"
#define NEW_BUTT "NEW_BUTT"
#define KICK_EQUIPE "KICK_EQUIPE"
#define NUM_CHAR "NUM_CHAR"
#define ROLE "ROLE"
#define ERREUR_REJOINDRE "ERREUR_REJOINDRE"
#define PSEUDO_REJOINT "PSEUDO_REJOINT"
#define MORT "MORT"

/* pour comparer sur ce nombre et pas les paramètres suivant */
#define TAILLE_REJ 16
#define TAILLE_DEP 11
#define TAILLE_TIR 3
#define TAILLE_KICK 11
